AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Notion Dashboard Stack
Parameters:
  NotionApiKey:
    Type: String
    Description: "Notion API Key"
    NoEcho: true
  WhoopUsername:
    Type: String
    Description: "Whoop Username"
    NoEcho: true
  WhoopPassword:
    Type: String
    Description: "Whoop Password"
    NoEcho: true
  LingqApiKey:
    Type: String
    Description: "LingQ API Key"
    NoEcho: true
Resources:
  NotionDashboardSynchronisationLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: NotionDashboardSynchronisationLambda
      Description: Synchronisation function for synchronising different services with Notion databases
      Handler: lambda.lambda_handler
      Environment:
        Variables:
          WHOOP_USERNAME: !Ref WhoopUsername
          WHOOP_PASSWORD: !Ref WhoopPassword
          NOTION_API_KEY: !Ref NotionApiKey
      Runtime: python3.13
      MemorySize: 256
      Timeout: 60
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        NotionDashboardSynchronisationSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(55 23 * * ? *)
            Name: NotionDashboardSyncSchedule
            Description: Triggers the Lambda function daily at 23:55
            Enabled: true
  